// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	dto "app/core/use-case/dto"

	mock "github.com/stretchr/testify/mock"
)

// GenerateReportUsecase is an autogenerated mock type for the GenerateReportUsecase type
type GenerateReportUsecase struct {
	mock.Mock
}

type GenerateReportUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *GenerateReportUsecase) EXPECT() *GenerateReportUsecase_Expecter {
	return &GenerateReportUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *GenerateReportUsecase) Execute(_a0 dto.GenerateReportDto) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.GenerateReportDto) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(dto.GenerateReportDto) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(dto.GenerateReportDto) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateReportUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GenerateReportUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 dto.GenerateReportDto
func (_e *GenerateReportUsecase_Expecter) Execute(_a0 interface{}) *GenerateReportUsecase_Execute_Call {
	return &GenerateReportUsecase_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *GenerateReportUsecase_Execute_Call) Run(run func(_a0 dto.GenerateReportDto)) *GenerateReportUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.GenerateReportDto))
	})
	return _c
}

func (_c *GenerateReportUsecase_Execute_Call) Return(_a0 string, _a1 error) *GenerateReportUsecase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GenerateReportUsecase_Execute_Call) RunAndReturn(run func(dto.GenerateReportDto) (string, error)) *GenerateReportUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenerateReportUsecase creates a new instance of GenerateReportUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerateReportUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenerateReportUsecase {
	mock := &GenerateReportUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
