// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gen "app/infra/adapters/grpc/services/report/gen"
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ReportServiceClient is an autogenerated mock type for the ReportServiceClient type
type ReportServiceClient struct {
	mock.Mock
}

type ReportServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportServiceClient) EXPECT() *ReportServiceClient_Expecter {
	return &ReportServiceClient_Expecter{mock: &_m.Mock}
}

// GenerateReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportServiceClient) GenerateReport(ctx context.Context, in *gen.ReportRequest, opts ...grpc.CallOption) (*gen.ReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReport")
	}

	var r0 *gen.ReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ReportRequest, ...grpc.CallOption) (*gen.ReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ReportRequest, ...grpc.CallOption) *gen.ReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ReportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportServiceClient_GenerateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReport'
type ReportServiceClient_GenerateReport_Call struct {
	*mock.Call
}

// GenerateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - in *gen.ReportRequest
//   - opts ...grpc.CallOption
func (_e *ReportServiceClient_Expecter) GenerateReport(ctx interface{}, in interface{}, opts ...interface{}) *ReportServiceClient_GenerateReport_Call {
	return &ReportServiceClient_GenerateReport_Call{Call: _e.mock.On("GenerateReport",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ReportServiceClient_GenerateReport_Call) Run(run func(ctx context.Context, in *gen.ReportRequest, opts ...grpc.CallOption)) *ReportServiceClient_GenerateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*gen.ReportRequest), variadicArgs...)
	})
	return _c
}

func (_c *ReportServiceClient_GenerateReport_Call) Return(_a0 *gen.ReportResponse, _a1 error) *ReportServiceClient_GenerateReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportServiceClient_GenerateReport_Call) RunAndReturn(run func(context.Context, *gen.ReportRequest, ...grpc.CallOption) (*gen.ReportResponse, error)) *ReportServiceClient_GenerateReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportServiceClient creates a new instance of ReportServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportServiceClient {
	mock := &ReportServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
