// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeReportServiceServer is an autogenerated mock type for the UnsafeReportServiceServer type
type UnsafeReportServiceServer struct {
	mock.Mock
}

type UnsafeReportServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeReportServiceServer) EXPECT() *UnsafeReportServiceServer_Expecter {
	return &UnsafeReportServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedReportServiceServer provides a mock function with given fields:
func (_m *UnsafeReportServiceServer) mustEmbedUnimplementedReportServiceServer() {
	_m.Called()
}

// UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedReportServiceServer'
type UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedReportServiceServer is a helper method to define mock.On call
func (_e *UnsafeReportServiceServer_Expecter) mustEmbedUnimplementedReportServiceServer() *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call {
	return &UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedReportServiceServer")}
}

func (_c *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call) Run(run func()) *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call) Return() *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call) RunAndReturn(run func()) *UnsafeReportServiceServer_mustEmbedUnimplementedReportServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeReportServiceServer creates a new instance of UnsafeReportServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeReportServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeReportServiceServer {
	mock := &UnsafeReportServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
